title: Awenturyn
description: Awenturyn (aventurine) to odrębny, brakujący poziom w teorii rozwoju organizacji, rozwiązujący kontradykcje etapu Zielonego, niezależnie od wdrożenia turkusu. 
url: https://awenturyn.org
baseurl: ""
lang: pl
timezone: Europe/Warsaw
permalink: pretty
author: Sebastian Rudnicki
og_image: /assets/og.png

theme: aventurine-theme

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - docs
  - scripts
  - .githooks
  - .bundle
  - .jekyll-cache
  - _site
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - .ruby-version
  - .mdlrc
