title: Awenturyn
description: Awenturyn to odrębny, brakujący poziom rozwoju organizacji w teorii rozwoju organizacji, rozwiązujący sprzeczności etapu Zielonego, niezależnie od wdrożenia turkusu.
website_description: "Awenturyn.org: edukacyjna definicja Awenturynu - brakującego poziomu rozwoju organizacji w teorii rozwoju organizacji, który po Zielonym rozwiązuje sprzeczności i redukuje koszty, straty, ryzyka i nadużycia bez wdrożenia turkusu."
og_description: "Awenturyn: brakujący poziom organizacji po Zielonym. Rozwiązuje sprzeczności etapu Zielonego; mniej kosztów, strat i ryzyka bez turkusu."
url: https://awenturyn.org
baseurl: ""
lang: pl
timezone: Europe/Warsaw
permalink: pretty
author: Sebastian Rudnicki
og_image: /assets/og.png

theme: aventurine-theme

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - docs
  - scripts
  - .githooks
  - .bundle
  - .jekyll-cache
  - _site
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - .ruby-version
  - .mdlrc
